services:

  # Esse banco de dados se tornou o DB principal, sendo ReadOnly
  db-central:
    image: postgres:18-alpine3.22
    container_name: emotion-db-central
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: emotion
    networks:
      - emotion-network
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
  
  redis:
    image: redis:8.2.2-alpine
    container_name: emotion-redis
    networks:
      - emotion-network
    restart: always
    ports:
      - "6379:6379"

volumes:
  pgdata:

networks:
  emotion-network:
    name: emotion-network

